services:
  database:
    container_name: database
    image: mariadb:10.4.21
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: symfony_docker
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    # volumes:
    #  - ./php/artifacts_5:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./php/artifacts_5:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - php
