services:
  database:
    container_name: database
    image: mariadb:10.4.21
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: symfony_docker
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    #ports:
    #  - '4306:3306'
    volumes:
      - ./back/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  php-nginx:
    container_name: php-nginx
    build:
      context: ./back/php-nginx
    ports:
      - '8081:80'
    volumes:
      - ./back/php-nginx/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
  node:
    container_name: node
    build:
      context: ./front/node
    ports:
      - '8082:80'
  general:
    container_name: general
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./general/nginx/default.conf:/etc/nginx/conf.d/default.conf